version: "3"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql
